---
abstract: unknown
author:
  - 'Ben Booth <benwbooth@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Xen-API
no_index:
  directory:
    - t
    - inc
requires:
  Devel::REPL: 0
  IO::Prompt: 0
  Net::OpenSSH: 0
  Number::Format: 0
  RPC::XML: 0
  Test::More: 0
version: 0.08
